### ISSUE TITLE
add website to Additional Information

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/jkan#1]
Since we've [dropped EveryPolitician data in there](https://mysociety.github.io/jkan/datasets/?organization=everypolitician), it would be lovely to explicitly link to [everypolitician.org](http://everypolitician.org/) because we provide lots of potentially useful information both _about_ the data and _how_ to use it (e.g., that we have libraries for working with it/keeping it up to date)... which isn't obvious just from grabbing the data itself.

"More information:" maybe?  Or (less hinty-helpy) "Website:"

Suggestion/example:

![jkan](https://cloud.githubusercontent.com/assets/111320/23704572/8988c1ba-03fd-11e7-9933-12b46f0ebcef.png)

(oops no www needed on URL there)

**Comment by jacksonj04** [comment]
Fixed in https://github.com/mysociety/jkan/commit/b5bd53a68abde458db63f46184700babedb95e72

**Comment by davewhiteland** [comment]
Thanks @jacksonj04 :-)  

![screen shot 2017-03-08 at 15 34 30](https://cloud.githubusercontent.com/assets/111320/23710489/d6b71060-0414-11e7-8d85-24c3318dfdec.png)
