### ISSUE TITLE
Launch

### ISSUE THREAD

**Issue by ajparsons** [mysociety/jkan#6]
Tasks to be completed before it is 'launched':

Add - Data & APIs Link to footer of:

- [x] parser.theyworkforyou.com – @zarino / @wrightmartin – https://github.com/mysociety/parlparse/pull/94
- [x] research footer
- [x] researchsites template (waiting on mailing list change)
- [x] www.mysociety.org – @zarino / @wrightmartin 

Add this text 'APIs and datasets for other mySociety services can be found on our data portal - http://data.mysociety.org/' to:

- [x] parser.theyworkforyou.com – @zarino / @wrightmartin – https://github.com/mysociety/parlparse/pull/94
- [x] www.theyworkforyou.com/api  – @zarino / @wrightmartin – https://github.com/mysociety/theyworkforyou/pull/1350

Merge:
- [x] Update to EveryPolitician docs - https://github.com/everypolitician/everypolitician-docs/pull/41

Write: 
- [x] Blog Post on Data Portal
- [x] Blog Post on EveryPolitician R Repo

Review (@MyfanwyNixon):
- [x] Blog Post on Data Portal - https://blogs.mysociety.org/mysociety/wp-admin/post.php?post=41658&action=edit
- [x] Blog Post on EveryPolitician R Repo - https://blogs.mysociety.org/mysociety/wp-admin/post.php?post=41659&action=edit

Publish:
- [x] Blog Post on Data Portal
- [x] Blog Post on EveryPolitician R Repo

**Comment by MyfanwyNixon** [comment]
Blog posts are both fine from my point of view. Each needs an image though. Happy to source these, unless you'd prefer to do so yourself, Alex.

**Comment by ajparsons** [comment]
@MyfanwyNixon : I am very bad at finding images, so I'm happy to leave the task of finding good images for horribly abstract posts to you!

**Comment by MyfanwyNixon** [comment]
Hooray - well at least I have plenty of experience...

**Comment by dracos** [comment]
This is what you get if the JavaScript doesn't load. We shouldn't launch a site that requires JavaScript in order to show basic information.
<img alt="not much information without JS" src="https://user-images.githubusercontent.com/154364/38019484-96ad9950-326f-11e8-9672-3b0fa44cd8fb.png" width="50%">
