### ISSUE TITLE
Images on /sources/ not there in Chrome, overlapping in Safari

### ISSUE THREAD

**Issue by dracos** [mysociety/jkan#7]
<img src="https://user-images.githubusercontent.com/154364/38021556-178e63b0-3275-11e8-9f05-0f3796f3ad5f.png" width="45%"> <img src="https://user-images.githubusercontent.com/154364/38021567-1e79890c-3275-11e8-9b22-5b0236f722a2.png" width="45%">

**Comment by ajparsons** [comment]
Addressed by ef85039a687db83384bd9f21b0715df31b9a61f9 

Problematic formatting removed, but more generally sources page removed from navigation as purpose unclear. Should be revisited if we start to host data from more sources.
